Revert "Update simplecov gem to 0.18.0"
cc-test-reporter fail with:

Error: json: cannot unmarshal object into Go struct field input.coverage of type []formatters.NullInt

This reverts commit 12e731c98b2ab67cd2e07096a1ac993d048230b1.